title: Trung Nguyen # your name (or website title) here
logo: "/images/avatar_new.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify">
  Computer Science Graduate and Data Science Postgraduate. I am currently a Machine Learning Engineer at Viettel Cyberspace Center.
  <br><br>
  Despite all the hype Machine Learning and AI have, I am much more interested in how simple yet effective statistics and visualization can unveil the most helpful pattern in our life. In my opinion, pipeline and objective come first, model comes later. 
  <br><br>
  </p>
  <a href="https://www.linkedin.com/in/nghetrung">My LinkedIn Profile</a>
  <br><br>
  <a href="/pdf/Nguyen-Minh-Trung-Resume-2025.pdf">My Resume</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
